[project]
name = "myproject"
version = "0.1.0"
description = ""
authors = [
    {name = "apolovko2023-bit",email = "apolovko2023@itcollege.lviv.ua"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.33.1,<3.0.0)",
    "flask (>=3.1.3,<4.0.0)"
]

[tool.poetry]
packages = [{include = "myproject", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "mypy (>=1.20.2,<2.0.0)"
]
docs = [
    "mkdocs (>=1.6.1,<2.0.0)"
]
